name: 'Git Cloud Watch Logger'
description: 'Log git commits to cloud watch'
inputs:
  log-group-name:
    description: 'cloudwatch log group name'
    required: true
    default: 'GITHUB_COMMITS'
  log-stream-name:
    description: 'cloudwatch log stream name'
    required: true
    default: 'GITHUB_COMMITS'
  filter-keys:
    description: 'json to filter github push event data'
    required: true
    default: '{"repository":{"name":""},"head_commit":{"committer":{"email":"","name":""},"timestamp":""}}'
runs:
  using: 'node12'
  main: 'index.js'